{{- if not .Values.freeradius.existingSecret }}
{{- if and (contains "CHANGE_ME" .Values.freeradius.secret) (not (eq .Release.Name "test")) }}
{{- fail "freeradius.secret must be changed from default value. Use --set freeradius.secret=YOUR_SECRET" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
type: Opaque
stringData:
  radius-secret: {{ .Values.freeradius.secret | quote }}
  healthcheck-secret: {{ .Values.freeradius.healthcheckSecret | quote }}
  {{- if .Values.mysql.enabled }}
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  {{- else }}
  mysql-password: {{ .Values.externalMysql.password | quote }}
  {{- end }}
{{- end }}
