apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
    app.kubernetes.io/component: radius-server
  {{- with .Values.freeradius.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.freeradius.service.type }}
  {{- if .Values.freeradius.service.loadBalancerIP }}
  {{- if semverCompare "<1.24.0" .Capabilities.KubeVersion.Version }}
  loadBalancerIP: {{ .Values.freeradius.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.freeradius.service.ports.auth }}
      targetPort: radius-auth
      protocol: UDP
      name: radius-auth
    - port: {{ .Values.freeradius.service.ports.acct }}
      targetPort: radius-acct
      protocol: UDP
      name: radius-acct
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}-status
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
    app.kubernetes.io/component: status
spec:
  type: ClusterIP
  ports:
    - port: 18121
      targetPort: radius-status
      protocol: UDP
      name: radius-status
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}
