apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: freeradius
  namespace: freeradius
  labels:
    app.kubernetes.io/name: freeradius
    app.kubernetes.io/component: radius-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: freeradius
