apiVersion: v1
kind: ServiceAccount
metadata:
  name: freeradius
  namespace: freeradius
  labels:
    app.kubernetes.io/name: freeradius
    app.kubernetes.io/component: radius-server
automountServiceAccountToken: false
